### PR TITLE
Removed redirect html tag

### PR DESCRIPTION
**Pull request by dilekuzulmez**
I removed all the {:target="_blank"}  in Markdown files. #605

### CODE REVIEW

**Review by kdaily — COMMENTED** [review]
Thank you so much! There's one issue - this is against the `master` branch, not the `gh-pages` branch. We are in the midst of a migration. Let me see if there's an easy way to get all of the correct changes you made such that they don't conflict with the other changes in that branch.

**Comment by dilekuzulmez** [comment]
> Thank you so much! There's one issue - this is against the `master` branch, not the `gh-pages` branch. We are in the midst of a migration. Let me see if there's an easy way to get all of the correct changes you made such that they don't conflict with the other changes in that branch.

Is there anything i need to do ?

**Comment by kdaily** [comment]
I just opened a pull request against your changes that addresses the conflicts. If you can accept that, we can then merge this one in. You can review it here:

https://github.com/dilekuzulmez/synapseDocs/pull/1

Thanks again!

**Comment by dilekuzulmez** [comment]
> I just opened a pull request against your changes that addresses the conflicts. If you can accept that, we can then merge this one in. You can review it here:
> 
> [dilekuzulmez#1](https://github.com/dilekuzulmez/synapseDocs/pull/1)
> 
> Thanks again!


You are welcome :)

**Review by kdaily — APPROVED** [review]
Thanks again, looks good!

**Pull request merged**
