### PR TITLE
Adding new category called Scientific Computing

### LINKED ISSUE #800: DOC: Add service catalog documentation
#### Location of the Documentation

There should be a new documentation domain called 'scientific computing' with sub parts for using resources in sc.sageit.org, which is accessed through Synapse. This is currently missing.

#### Problem

We need a space for service catalog documentation that is general and not specific to a project.

#### Suggested Fix

I'll start with some security docs.

### PR DESCRIPTION
**Pull request by ahayden**
This change adds a Jekyll category  for 'scientific computing' via resources generated through Synapse directly, namely through the service catalog attached to Synapse. Please review/comment on alternative ways to organize this!

- [x] Fixes #800 
- [ ] If you are creating a page, did you follow the instructions [here](https://github.com/Sage-Bionetworks/synapseDocs#creating-a-page)?
- [x] Did you follow the [style guide](https://github.com/Sage-Bionetworks/synapseDocs#style-guide)?
- [x] Did you include a description of your changes or additions in this pull request?
- [ ] (Optional) Did you examine your build locally (instructions [here](https://help.github.com/en/github/working-with-github-pages/))

### CODE REVIEW

**Review by tthyer — APPROVED** [review]

**Review by kelshmo — APPROVED** [review]

**Review by karawoo — APPROVED** [review]

**Comment by kelshmo** [comment]
This PR creates a new category for #802 and should only be merged if it is decided that #802 should live in the public facing synapse docs.

**Comment by Aryllen** [comment]
> This PR creates a new category for #802 and should only be merged if it is decided that #802 should live in the public facing synapse docs.

This is a good point. I think we might be getting close to the stage where the Synapse docs should have this information; The beta for this is already live in the AD Knowledge Portal.

**Comment by ahayden** [comment]
The Service Catalog dev team is thinking to include security documentation in an AWS marketplace onboarding workflow rather than Synapse Docs because though it may not be relevant to all Synapse users, it will be relevant to those who interact with the marketplace flow.

**Comment by ahayden** [comment]
Closing as #802 will not be merged

**Pull request closed without merging**
