### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by kdaily**
Seems to be a problem in travis. bumping RVM version.

### CODE REVIEW

**Comment by kdaily** [comment]
This passed @meredithslota, think this will fix our problem. I couldn't find a reason that `rvm 2.1` was deprecated though.

**Comment by meredithslota** [comment]
FOUND IT. On this page (https://docs.travis-ci.com/user/languages/ruby#specifying-ruby-versions-and-implementations) they state:

"Bundler 2.0 #
On January 3rd 2019 the Bundler team released Bundler 2.0 which dropped support for Ruby versions 2.2 and older, and added a new dependency on RubyGems 3.0.0.". 

So we should ensure to version-bump to higher than 2.2.

**Comment by kdaily** [comment]
Looks like this might be the culprit:

https://github.com/rvm/rvm/issues/4566

**Comment by kdaily** [comment]
@meredithslota changes addressed - I will test using a later version of Ruby after the other PRs are in for our objective milestones!

**Pull request merged**
